language: python
python:
  - "3.4"
  - "3.5"
branches:
  only:
    - master
    - develop
    - /^release-v(\d+.){0,2}\d+$/
install:
  - sudo pip install flake8
before_script:
  - "flake8 cactus.py beam.py messages.py models.py"
script: nosetests
